media-user-token: "ArUNzWfuGPDpCWQaJOa2i9mfKzcw7WDh4chLQWEjPAsH+hh1f1WSQY68j7IWZ6bOTDLs2xZIqCmmIZanCeb/X5tinzV5sxhbBuDRGep6paS7YrDraYLq1cSOrJ4ZmVVTazjbt6AjJTUaCOLwwyTs9oF0MQCh/+gQRcAmdnw8b0QzPj8ao3SRLV8hUZ722635phWLuhnP0MKhfgScAj9az1Zj4Lhy8kVHRnoyrOhvidDu99Md/Q=="
# If you need to obtain the lyrics, need to change it
authorization-token: "your-authorization-token"
# You don't need to change it; it can automatically obtain token
language: ""
# supportedLanguage by each storefront --> https://gist.github.com/itouakirai/c8ba9df9dc65bd300094103b058731d0
lrc-type: "lyrics"
# lyrics or syllable-lyrics
lrc-format: "lrc"
# lrc or ttml
embed-lrc: false
# Unable to embed ttml lyrics
save-lrc-file: true
save-artist-cover: true
save-animated-artwork: true
# If enabled, requires ffmpeg
emby-animated-artwork: true
# If enabled, requires ffmpeg
embed-cover: false
cover-size: 10000x10000
cover-format: original
# jpg png or original
alac-save-folder: /mnt/g/music
atmos-save-folder: /mnt/g/music
check: ""
# API or .txt
force-api: false
decrypt-m3u8-port: "127.0.0.1:10020"
get-m3u8-port: "127.0.0.1:20020"
get-m3u8-from-device: true
# set 'all' to retrieve all m3u8, and set 'hires' to only detect hires m3u8.
get-m3u8-mode: hires
# all hires
alac-max: 192000
# 192000 96000 48000 44100
atmos-max: 2768
# 2768 2448
limit-max: 200
# {AlbumId} {AlbumName} {ArtistName} {ReleaseDate} {ReleaseYear} {UPC} {Copyright} {Quality} {Codec} {Tag} {RecordLabel}
# example: {ReleaseYear} - {ArtistName} - {AlbumName}({AlbumId})({UPC})({Copyright}){Codec}
album-folder-format: "{ReleaseDate} {AlbumName} {AlbumId}"
# {PlaylistId} {PlaylistName} {ArtistName} {Quality} {Codec} {Tag}
playlist-folder-format: "{ReleaseDate} {AlbumName} {AlbumId}"
# {SongId} {SongNumer} {SongName} {DiscNumber} {TrackNumber} {Quality} {Codec} {Tag}
# example: Disk {DiscNumber} - Track {TrackNumber} {SongName} [{Quality}]{{Tag}}"
song-file-format: "{SongNumer} {SongName}"
# {ArtistId} {ArtistName}/{UrlArtistName}
# if artist-folder-format set "",will not make artist folder
artist-folder-format: "{ArtistName}"
# if set "" will not add tag
explicit-choice: "[E]"
clean-choice: "[C]"
apple-master-choice: "[M]"
# if set true,for playlst,will use songinfo for meta #albumname track disk
use-songinfo-for-playlist: false
# if set true,will download album cover for playlist
dl-albumcover-for-playlist: false
